import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  buildStoryUrl,
  filterByProject,
  parseFileImport,
  prepareImport,
  sniffImport,
} from "../src/import/index.ts";
import { parseCsv } from "../src/import/csv.ts";

const CSV = [
  "Summary,Issue key,Issue id,Priority,Description,Status",
  "\"Track Common components chart dependencies\",\"PAY-9053\",71245,High,\"h2. Risks",
  "||*Chart*||*Minimum Version*||",
  "|chart-java|6.1.1|",
  "{{/charts/apim}} and {*bold*} text [chart guide|https://example.com]\",In Progress",
  "\"Calculate SLC Esp waiver breakdown\",\"PAY-9015\",71244,Medium,_Italic_ with *stars* and # item,Open",
  "\"Skipped row (no key)\",\"\",71243,Low,no key here,Open",
].join("\r\n") + "\r\n";

describe("sniffImport", () => {
  it("detects csv by headers", () => {
    assert.equal(sniffImport(CSV), "csv");
  });

  it("detects xml/rss even with a leading comment", () => {
    const xml =
      "<!-- RSS generated by JIRA (Not on a server) at 2026-09-15 -->\n" +
      "<?xml version=\"0.92\"?><rss version=\"0.92\"><channel><title>Filter</title></channel></rss>";
    assert.equal(sniffImport(xml), "xml");
  });

  it("rejects unknown content", () => {
    assert.equal(sniffImport("hello, just some text"), null);
  });
});

describe("parseCsv", () => {
  it("handles quotes, embedded newlines and CRLF", () => {
    const rows = parseCsv("\"a,\"\"b\"\"\r\nc\",d\r\ne,f\r\n");
    assert.equal(rows.length, 2);
    assert.equal(rows[0]![0], "a,\"b\"\nc");
    assert.deepEqual(rows[1], ["e", "f"]);
  });
});

describe("parseJiraCsv → parseFileImport", () => {
  it("parses a Jira export and cleans wiki markup", () => {
    const result = parseFileImport(CSV);
    assert.equal(result.source, "csv");
    assert.equal(result.skipped, 1);
    assert.equal(result.stories.length, 2);

    const first = result.stories[0]!;
    assert.equal(first.key, "PAY-9053");
    assert.equal(
      first.title,
      "PAY-9053 - Track Common components chart dependencies",
    );
    assert.ok(first.description.includes("Risks"));
    assert.ok(first.description.includes("chart-java | 6.1.1"));
    assert.ok(first.description.includes("/charts/apim"));
    assert.ok(first.description.includes("bold text"));
    assert.ok(first.description.includes("chart guide"));
    assert.ok(!first.description.includes("example.com"));

    const second = result.stories[1]!;
    assert.equal(second.key, "PAY-9015");
    assert.ok(second.description.includes("Italic with stars"));
    assert.ok(second.description.includes("item"));
  });

  it("keeps descriptions within the story limit", () => {
    const long = `h1. Long\n${"word ".repeat(200)}`;
    const csv = `Summary,Issue key,Description\nX,PAY-1,"${long}"`;
    const result = parseFileImport(csv);
    assert.ok(result.stories[0]!.description.length <= 500);
  });

  it("normalises lowercase keys to upper", () => {
    const csv = "Summary,Issue key,Description\nX,pay-0192,desc";
    const result = parseFileImport(csv);
    assert.equal(result.stories[0]!.key, "PAY-0192");
  });

  it("throws on unrecognised content", () => {
    assert.throws(() => parseFileImport("Foo,Bar\n1,2"), /Unrecognised file/);
  });

  it("throws when a CSV has no issue key column", () => {
    assert.throws(
      () => parseFileImport("Summary,Description\nX,desc"),
      /Unrecognised CSV/,
    );
  });
});

describe("parseJiraRss → parseFileImport", () => {
  it("parses an issue-style RSS with a title-key and link", () => {
    const xml = `<?xml version="1.0"?>
<rss version="0.92"><channel><title>Filter: F&amp;P</title>
<item>
<title>PAY-9053 - Track Common components chart dependencies</title>
<link>https://hmcts.atlassian.net/browse/PAY-9053</link>
<guid isPermaLink="false">stuff</guid>
<description><![CDATA[Some &amp; details here]]></description>
</item>
</channel></rss>`;
    const result = parseFileImport(xml);
    assert.equal(result.source, "xml");
    assert.equal(result.stories.length, 1);
    const story = result.stories[0]!;
    assert.equal(story.key, "PAY-9053");
    assert.equal(
      story.title,
      "PAY-9053 - Track Common components chart dependencies",
    );
    assert.equal(story.description, "Some & details here");
    assert.equal(story.url, "https://hmcts.atlassian.net/browse/PAY-9053");
  });

  it("parses an issue-style RSS that has a <key> element", () => {
    const xml = `<?xml version="1.0"?><rss version="0.92"><channel>
<item>
<title>[PAY-6357] Update coverage docs</title>
<key>PAY-6357</key>
<link>https://hmcts.atlassian.net/browse/PAY-6357</link>
<guid>https://hmcts.atlassian.net/browse/PAY-6357</guid>
<description>Nothing here.</description>
</item>
</channel></rss>`;
    const result = parseFileImport(xml);
    assert.equal(result.stories.length, 1);
    assert.equal(result.stories[0]!.key, "PAY-6357");
    assert.equal(result.stories[0]!.title, "PAY-6357 - Update coverage docs");
  });

  it("skips comment items in a filter activity feed", () => {
    const xml = `<?xml version="1.0"?><rss version="0.92"><channel>
<item>
<title>RE: [PAY-9015] Calculate SLC Esp waiver breakdown</title>
<link>https://hmcts.atlassian.net/browse/PAY-9015?focusedCommentId=128157</link>
<guid isPermaLink="false">comment-128157</guid>
<description>A comment body.</description>
</item>
</channel></rss>`;
    const result = parseFileImport(xml);
    assert.equal(result.stories.length, 0);
    assert.equal(result.skipped, 1);
  });

  it("throws on XML without items", () => {
    assert.throws(
      () => parseFileImport("<rss><channel><title>x</title></channel></rss>"),
      /no <item>/,
    );
  });
});

describe("prepareImport / config", () => {
  const csv = "Summary,Issue key\nPAY-9053 x,PAY-9053\nFOO-1 y,FOO-1";

  it("links urls from jiraHost and handles a missing scheme", () => {
    const bare = prepareImport(csv, { jiraHost: "hmcts.atlassian.net" });
    assert.equal(bare.stories[0]!.url, "https://hmcts.atlassian.net/browse/PAY-9053");

    const full = prepareImport(csv, { jiraHost: "https://hmcts.atlassian.net/" });
    assert.equal(full.stories[0]!.url, "https://hmcts.atlassian.net/browse/PAY-9053");
  });

  it("leaves urls unset without a host", () => {
    const result = prepareImport(csv, {});
    assert.equal(result.stories[0]!.url, undefined);
  });

  it("filters to the configured project and keeps order", () => {
    const result = prepareImport(csv, { jiraProjectKey: "PAY" });
    assert.equal(result.stories.length, 1);
    assert.equal(result.stories[0]!.key, "PAY-9053");
  });

  it("keeps everything when no project key is set", () => {
    const result = prepareImport(csv, {});
    assert.equal(result.stories.length, 2);
  });

  it("buildStoryUrl and filterByProject", () => {
    assert.equal(buildStoryUrl("PAY-9053", "https://jira.example.com/"), "https://jira.example.com/browse/PAY-9053");
    assert.equal(buildStoryUrl("PAY-9053", null), undefined);
    const filtered = filterByProject(
      [{ key: "PAY-1", title: "a", description: "" }, { key: "X-9", title: "b", description: "" }],
      "pay",
    );
    assert.equal(filtered.length, 1);
    assert.equal(filtered[0]!.key, "PAY-1");
  });
});